# Thanks to https://github.com/jlumbroso/lfs-to-github-pages
name: GitHub Pages Build

on:
    push:
        branches:
            - master # Set a branch to deploy

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: 🛎️ Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
                  lfs: true # Fetch large files

            - name: ❌ Turn off LFS
              run: >-
                  git lfs uninstall;
                  rm -Rf .git;
                  rm -Rf repo-pkgbuild;
                  rm -Rf docker;
                  rm .gitattributes;
                  rm .gitignore;
                  rm generate-env.sh;
                  rm LICENCE;
                  rm packages;
                  rm README.md;
                  rm run-build-docker.sh;

            - name: 🚀 Deploy to `gh-pages` branch
              uses: peaceiris/actions-gh-pages@v3.9.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./
                  publish_branch: gh-pages
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
